export const LISTENER_CMDS = {
	API: "API",
	PARAMS: "PARAMS",
	ACCOUNT_CONTEXT: "ACCOUNT_CONTEXT",

	//Forms SDK Functions
	GETFORMFIELD: "GETFORMFIELD",
	GETFORMTABLEFIELD: "GETFORMTABLEFIELD",
	UPDATEFORM: "UPDATEFORM",
	UPDATEFORMTABLE: "UPDATEFORMTABLE",

	//Client SDK functions
	MESSAGE: "MESSAGE",
	CONFIRM: "CONFIRM",
	ALERT: "ALERT",
	REDIRECT: "REDIRECT",

	RETURN: "RETURN"
};
