export const LISTENER_CMDS = {
	API: "API",
	GET_CONTEXT: "GET_CONTEXT",
	RETURN: "RETURN",

	//Forms SDK Functions
	GET_FORM_FIELD: "GET_FORM_FIELD",
	UPDATE_FORM: "UPDATE_FORM",
	GET_TABLE: "GET_TABLE",
	GET_TABLE_ROW: "GET_TABLE_ROW",
	ADD_TABLE_ROW: "ADD_TABLE_ROW",
	ADD_TABLE_ROWS: "ADD_TABLE_ROWS",
	DELETE_TABLE_ROW: "DELETE_TABLE_ROW",
	TO_JSON: "TO_JSON",
	GET_TABLE_ROWS: "GET_TABLE_ROWS",
	GET_SELECTED_TABLE_ROWS: "GET_SELECTED_TABLE_ROWS",
	//Client SDK functions
	MESSAGE: "MESSAGE",
	CONFIRM: "CONFIRM",
	ALERT: "ALERT",
	REDIRECT: "REDIRECT",
	OPEN_PAGE: "OPEN_PAGE",

	//Formatter SDK Functions
	FORMAT_DATE: "FORMAT_DATE",
	FORMAT_DATE_TIME: "FORMAT_DATE_TIME",
	FORMAT_NUMBER: "FORMAT_NUMBER",
	FORMAT_CURRENCY: "FORMAT_CURRENCY",
	FORMAT_BOOLEAN: "FORMAT_BOOLEAN",

	//Application SDK functions
	GET_APP_VARIABLE: "GET_APP_VARIABLE",
	SET_APP_VARIABLE: "SET_APP_VARIABLE",

	//Application page sdk functions
	GET_PAGE_VARIABLE: "GET_PAGE_VARIABLE",
	SET_PAGE_VARIABLE: "SET_PAGE_VARIABLE",
	GET_PAGE_PARAMS: "GET_PAGE_PARAMS",
	GET_ALL_PAGE_PARAMS: "GET_ALL_PAGE_PARAMS",
	PAGE_ON_CLOSE: "PAGE_ON_CLOSE",
	OPEN_POPUP: "OPEN_POPUP",

	//Popup sdk functions
	GET_POPUP_PARAMS: "GET_POPUP_PARAMS",
	GET_ALL_POPUP_PARAMS: "GET_ALL_POPUP_PARAMS",
	CLOSE_POPUP: "CLOSE_POPUP",

	COMPONENT_GET: "COMPONENT_GET",
	COMPONENT_REFRESH: "COMPONENT_REFRESH",
	COMPONENT_SHOW: "COMPONENT_SHOW",
	COMPONENT_HIDE: "COMPONENT_HIDE",
	COMPONENT_ADD_EVENT_LISTENER: "COMPONENT_ADD_EVENT_LISTENER",

	// CC Refers to custom components
	CC_INITIALIZE: "CC_INITIALIZE",
	CC_WATCH_PARAMS: "CC_WATCH_PARAMS",

	// Decision table SDK functions
	DECISION_TABLE_EXECUTE: "DECISION_TABLE_EXECUTE",

	// Dataform methods
	DATAFORM_IMPORT_CSV: "DATAFORM_IMPORT_CSV",
	DATAFORM_OPEN_FORM: "DATAFORM_OPEN_FORM",

	DATAFORM_GET_FIELDS: "DATAFORM_GET_FIELDS",
	DATAFORM_GET_VIEW_FIELDS: "DATAFORM_GET_VIEW_FIELDS",

	DATAFORM_GET_ITEMS: "DATAFORM_GET_ITEMS",

	DATAFORM_CREATE_ITEM: "DATAFORM_CREATE_ITEM",
	DATAFORM_UPDATE_ITEM: "DATAFORM_UPDATE_ITEM",
	DATAFORM_GET_ITEM: "DATAFORM_GET_ITEM",
	DATAFORM_DELETE_ITEM: "DATAFORM_DELETE_ITEM",
	
	DATAFORM_DISCARD_ITEM: "DATAFORM_DISCARD_ITEM",
	DATAFORM_SUBMIT_ITEM: "DATAFORM_SUBMIT_ITEM",


	// Process methods
	PROCESS_OPEN_FORM: "PROCESS_OPEN_FORM",

	PROCESS_GET_FIELDS: "PROCESS_GET_FIELDS",
	PROCESS_GET_MYTASK_FIELDS: "PROCESS_GET_MYTASK_FIELDS",
	PROCESS_GET_PARTICIPATED_FIELDS: "PROCESS_GET_PARTICIPATED_FIELDS",
	PROCESS_GET_MY_ITEMS_FIELDS: "PROCESS_GET_MY_ITEMS_FIELDS",
	
	PROCESS_GET_MY_ITEMS: "PROCESS_GET_MY_ITEMS",
	PROCESS_GET_MY_TASKS_ITEMS: "PROCESS_GET_MY_TASKS_ITEMS",
	PROCESS_GET_PARTICIPATED_ITEMS: "PROCESS_GET_PARTICIPATED_ITEMS",
	PROCESS_GET_ADMIN_ITEMS: "PROCESS_GET_ADMIN_ITEMS",

	PROCESS_CREATE_ITEM: "PROCESS_CREATE_ITEM",
	PROCESS_UPDATE_ITEM: "PROCESS_UPDATE_ITEM",
	PROCESS_GET_ITEM: "PROCESS_GET_ITEM",
	PROCESS_DELETE_ITEM: "PROCESS_DELETE_ITEM",

	PROCESS_SUBMIT_ITEM: "PROCESS_SUBMIT_ITEM",
	PROCESS_REJECT_ITEM: "PROCESS_REJECT_ITEM",
	PROCESS_WITHDRAW_ITEM: "PROCESS_WITHDRAW_ITEM",
	PROCESS_SENDBACK_ITEM: "PROCESS_SENDBACK_ITEM",
	PROCESS_REASSIGN_ITEM: "PROCESS_REASSIGN_ITEM",
	PROCESS_RESTART_ITEM: "PROCESS_RESTART_ITEM",
	PROCESS_DISCARD_ITEM: "PROCESS_DISCARD_ITEM",

	// Board methods
	BOARD_IMPORT_CSV: "BOARD_IMPORT_CSV",
	BOARD_OPEN_FORM: "BOARD_OPEN_FORM",

	BOARD_GET_FIELDS: "BOARD_GET_FIELDS",
	BOARD_GET_VIEW_FIELDS: "BOARD_GET_VIEW_FIELDS",
	BOARD_GET_ITEMS: "BOARD_GET_ITEMS",

	BOARD_CREATE_ITEM: "BOARD_CREATE_ITEM",
	BOARD_UPDATE_ITEM: "BOARD_UPDATE_ITEM",
	BOARD_GET_ITEM: "BOARD_GET_ITEM",
	BOARD_DELETE_ITEM: "BOARD_DELETE_ITEM",

	BOARD_SUBMIT_ITEM: "BOARD_SUBMIT_ITEM",
	BOARD_DISCARD_ITEM: "BOARD_DISCARD_ITEM",
};

export const EVENT_TYPES = {
	COMPONENT_ON_MOUNT: "componentOnMount",
	CC_ON_PARAMS_CHANGE: "onCustomComponentParamsChange"
};

export const DEFAULTS = {
	POPUP_ID: "ACTIVE_POP_UP"
};
