const ORGANIZATION = '@' + 'shibi-snowball'

const CUSTOM_FORM_FIELD_SCRIPTS_PACKAGE_NAME = `${ORGANIZATION}/custom-form-field-scripts`
const CUSTOM_FORM_FIELD_MODEL_PACKAGE_NAME = `${ORGANIZATION}/custom-form-field-model`

export {
    CUSTOM_FORM_FIELD_SCRIPTS_PACKAGE_NAME,
    CUSTOM_FORM_FIELD_MODEL_PACKAGE_NAME,
}
