export const LISTENER_CMDS = {
	API: "API",
	PARAMS: "PARAMS",
	ACCOUNT_CONTEXT: "ACCOUNT_CONTEXT",

	//Forms SDK Functions
	GET_TABLE_DETAILS: "GET_TABLE_DETAILS",
	GET_FORM_FIELD: "GET_FORM_FIELD",
	GET_FORM_TABLE_FIELD: "GET_FORM_TABLE_FIELD",
	UPDATE_FORM: "UPDATE_FORM",
	UPDATE_FORM_TABLE: "UPDATE_FORM_TABLE",

	//Client SDK functions
	MESSAGE: "MESSAGE",
	CONFIRM: "CONFIRM",
	ALERT: "ALERT",
	REDIRECT: "REDIRECT",
	OPEN_PAGE: "OPEN_PAGE",

	//Formatter SDK Functions
	FORMAT_DATE: "FORMAT_DATE",
	FORMAT_DATE_TIME: "FORMAT_DATE_TIME",
	FORMAT_NUMBER: "FORMAT_NUMBER",
	FORMAT_CURRENCY: "FORMAT_CURRENCY",
	FORMAT_BOOLEAN: "FORMAT_BOOLEAN",

	GET_VARIABLE: "GET_VARIABLE",
	SET_VARIABLE: "SET_VARIABLE",

	RETURN: "RETURN"
};
