export const LISTENER_CMDS = {
    API: "API",
    PARAMS: "PARAMS",
    ACCOUNT_CONTEXT: "ACCOUNT_CONTEXT",
    //Forms SDK Functions
    GET_TABLE_DETAILS: "GET_TABLE_DETAILS",
    GET_FORM_FIELD: "GET_FORM_FIELD",
    GET_FORM_TABLE_FIELD: "GET_FORM_TABLE_FIELD",
    UPDATE_FORM: "UPDATE_FORM",
    UPDATE_FORM_TABLE: "UPDATE_FORM_TABLE",
    //Client SDK functions
    MESSAGE: "MESSAGE",
    CONFIRM: "CONFIRM",
    ALERT: "ALERT",
    REDIRECT: "REDIRECT",
    RETURN: "RETURN"
};
